const images = [
    "images/Bmd4 wallpaper.jpg",
    "images/Bmp3 wallpaper.jpg",
    "images/Bradley background.jpg",
    "images/Btr80 wallpaper.jpg",
    "images/Challenger 2 background.jpg",
    "images/F-15 wallpaper.jpg",
    "images/F-18 wallpaper.jpg",
    "images/f4 wallpaper.jpg",
    "images/F4u wallpaper.jpg",
    "images/F6f wallpaper.jpg",
    "images/F16 background.jpg",
    "images/f22 wallpaper.jpg",
    "images/F35 wallpaper.jpg",
    "images/Fw190 wallpaper.jpg",
    "images/kf51 panther.jpg",
    "images/Leclerc background.jpg",
    "images/Leo 2 background.jpg",
    "images/M1a2 Abrams background.jpg",
    "images/Merkava background.jpg",
    "images/Mig17 wallpaper.jpg",
    "images/Mig21 wallpaper.jpg",
    "images/Mig25 wallpaper.jpg",
    "images/Mig29 wallpaper.jpg",
    "images/Mig29 Flare wallpaper.jpg",
    "images/P47 wallpaper.jpg",
    "images/P51 wallpaper.jpg",
    "images/Puma background.jpg",
    "images/Spitfire wallpaper.jpg",
    "images/Su25 wallpaper.jpg",
    "images/Su27 wallpaper.jpg",
    "images/Su57 wallpaper.jpg",
    "images/T-72 wallpaper.jpg",
    "images/T-80 background.jpg",
    "images/t-72 4 wallpaper.jpg",
    "images/T-90 background.jpg",
    "images/Type 10 background.jpg",
    "images/Type 99 background.jpg",
    "images/Rafale wallpaper.jpg",
    "images/Eurofighter wallpaper.jpg",
    "images/J10 wallpaper.jpg",
    "images/J20 wallpaper.jpg",
    "images/J10 2 wallpaper.jpg",
    "images/kfir wallpaper.jpg", 
    "images/Mirage III wallpaper.jpg",
    "images/t-72 2 wallpaper.jpg",
    "images/t-72 3 wallpaper.jpg",
    "images/f-16 2 wallpaper.jpg",
    "images/f-22 2 wallpaper.jpg",
    "images/f-15 2 wallpaper.jpg",
    "images/challenger2 2 wallpaper.jpg",
    "images/challenger2 3 wallpaper.jpg",
    "images/p-47 2 wallpaper.jpg",
    "images/t-80 2 wallpaper.jpg",
    "images/f-15 3 wallpaper.jpg",
    "images/f-15 4 wallpaper.jpg",
    "images/f 16 3 wallpaper.jpg",
    "images/mig 35 wallpaper.jpg",
    "images/su 35 wallpaper.jpg"
  ];
  
  const encodedImages = images.map(img => encodeURI(img));
  
  const randomImage = encodedImages[Math.floor(Math.random() * encodedImages.length)];
  
  document.body.style.backgroundImage = `url('${randomImage}')`;
  